name: sokrio_users
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  connectivity_plus: ^7.0.0
  logger: ^2.6.1
  flutter_native_splash: ^2.4.6
  extended_image: ^10.0.1
  go_router: ^16.2.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  lottie: ^3.3.1
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network packages:
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1


# Flutter Splash Screen Setup
#
# This configuration helps you create a splash screen for your Flutter project.
#
# Instructions:
# 1. Add the following configuration to your pubspec.yaml file.
# 2. Run the command: fvm dart run flutter_native_splash:create
# 3. If you make any changes to the splash screen configuration, re-run the command.
#
# Current-Configuration:
flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.1
  hive_generator: ^2.0.1
  mockito: ^5.4.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/